In [1]:
%matplotlib inline
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.svm import SVC
from matplotlib import pyplot as plt
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.ensemble import AdaBoostClassifier,BaggingClassifier,GradientBoostingClassifier,\
RandomForestClassifier,VotingClassifier,HistGradientBoostingClassifier

In [3]:
df = pd.read_csv('Breast_cancer_data.csv')

In [4]:
df

mean_radius  mean_texture  ...  mean_smoothness  diagnosis
0          17.99         10.38  ...          0.11840          0
1          20.57         17.77  ...          0.08474          0
2          19.69         21.25  ...          0.10960          0
3          11.42         20.38  ...          0.14250          0
4          20.29         14.34  ...          0.10030          0
..           ...           ...  ...              ...        ...
564        21.56         22.39  ...          0.11100          0
565        20.13         28.25  ...          0.09780          0
566        16.60         28.08  ...          0.08455          0
567        20.60         29.33  ...          0.11780          0
568         7.76         24.54  ...          0.05263          1

[569 rows x 6 columns]

In [6]:
#df.info()

#### Features and Labels

In [7]:
X = df.drop('diagnosis', axis=1) 
y = df['diagnosis']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

## Logistic Regression

In [9]:
log_reg = LogisticRegression(max_iter=1000)
log_reg.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [10]:
log_reg.score(X_test, y_test)

0.9298245614035088

In [15]:
X_test

mean_radius  mean_texture  mean_perimeter  mean_area  mean_smoothness
204        12.47         18.60           81.09      481.9          0.09965
70         18.94         21.31          123.60     1130.0          0.09009
131        15.46         19.48          101.70      748.9          0.10920
431        12.40         17.68           81.47      467.8          0.10540
540        11.54         14.44           74.65      402.9          0.09984
..           ...           ...             ...        ...              ...
486        14.64         16.85           94.21      666.0          0.08641
75         16.07         19.65          104.10      817.7          0.09168
249        11.52         14.93           73.87      406.3          0.10130
238        14.22         27.85           92.55      623.9          0.08223
265        20.73         31.12          135.70     1419.0          0.09469

[114 rows x 5 columns]

In [16]:
log_reg_pred = log_reg.predict(X_test)
log_reg_pred

array([1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 0, 0])

In [18]:
Logistic_Regression = pd.DataFrame(X_test)
Logistic_Regression['prediction'] = log_reg_pred
Logistic_Regression

mean_radius  mean_texture  ...  mean_smoothness  prediction
204        12.47         18.60  ...          0.09965           1
70         18.94         21.31  ...          0.09009           0
131        15.46         19.48  ...          0.10920           0
431        12.40         17.68  ...          0.10540           1
540        11.54         14.44  ...          0.09984           1
..           ...           ...  ...              ...         ...
486        14.64         16.85  ...          0.08641           1
75         16.07         19.65  ...          0.09168           0
249        11.52         14.93  ...          0.10130           1
238        14.22         27.85  ...          0.08223           0
265        20.73         31.12  ...          0.09469           0

[114 rows x 6 columns]

## AdaBoostClassifier

In [11]:
adaboost = AdaBoostClassifier()
adaboost.fit(X_train, y_train)

AdaBoostClassifier()

In [12]:
adaboost.score(X_test, y_test)

0.9385964912280702

In [13]:
X_test

mean_radius  mean_texture  mean_perimeter  mean_area  mean_smoothness
204        12.47         18.60           81.09      481.9          0.09965
70         18.94         21.31          123.60     1130.0          0.09009
131        15.46         19.48          101.70      748.9          0.10920
431        12.40         17.68           81.47      467.8          0.10540
540        11.54         14.44           74.65      402.9          0.09984
..           ...           ...             ...        ...              ...
486        14.64         16.85           94.21      666.0          0.08641
75         16.07         19.65          104.10      817.7          0.09168
249        11.52         14.93           73.87      406.3          0.10130
238        14.22         27.85           92.55      623.9          0.08223
265        20.73         31.12          135.70     1419.0          0.09469

[114 rows x 5 columns]

In [14]:
adaboost_pred = adaboost.predict(X_test)
adaboost_pred

array([1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1,
       0, 1, 1, 0])

In [19]:
AdaBoost_Classifier = pd.DataFrame(X_test)
AdaBoost_Classifier['prediction'] = adaboost_pred
AdaBoost_Classifier

mean_radius  mean_texture  ...  mean_smoothness  prediction
204        12.47         18.60  ...          0.09965           1
70         18.94         21.31  ...          0.09009           0
131        15.46         19.48  ...          0.10920           0
431        12.40         17.68  ...          0.10540           1
540        11.54         14.44  ...          0.09984           1
..           ...           ...  ...              ...         ...
486        14.64         16.85  ...          0.08641           1
75         16.07         19.65  ...          0.09168           0
249        11.52         14.93  ...          0.10130           1
238        14.22         27.85  ...          0.08223           1
265        20.73         31.12  ...          0.09469           0

[114 rows x 6 columns]

## BaggingClassifier

In [20]:
bagging_clf = BaggingClassifier()
bagging_clf.fit(X_train, y_train)

BaggingClassifier()

In [21]:
bagging_clf.score(X_test, y_test)

0.9122807017543859

In [22]:
X_test

mean_radius  mean_texture  mean_perimeter  mean_area  mean_smoothness
204        12.47         18.60           81.09      481.9          0.09965
70         18.94         21.31          123.60     1130.0          0.09009
131        15.46         19.48          101.70      748.9          0.10920
431        12.40         17.68           81.47      467.8          0.10540
540        11.54         14.44           74.65      402.9          0.09984
..           ...           ...             ...        ...              ...
486        14.64         16.85           94.21      666.0          0.08641
75         16.07         19.65          104.10      817.7          0.09168
249        11.52         14.93           73.87      406.3          0.10130
238        14.22         27.85           92.55      623.9          0.08223
265        20.73         31.12          135.70     1419.0          0.09469

[114 rows x 5 columns]

In [23]:
bagging_clf_pred = bagging_clf.predict(X_test)
bagging_clf_pred

array([1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 0])

In [24]:
Bagging_Classifier = pd.DataFrame(X_test)
Bagging_Classifier['prediction'] = bagging_clf_pred
Bagging_Classifier

mean_radius  mean_texture  ...  mean_smoothness  prediction
204        12.47         18.60  ...          0.09965           1
70         18.94         21.31  ...          0.09009           0
131        15.46         19.48  ...          0.10920           0
431        12.40         17.68  ...          0.10540           1
540        11.54         14.44  ...          0.09984           1
..           ...           ...  ...              ...         ...
486        14.64         16.85  ...          0.08641           1
75         16.07         19.65  ...          0.09168           0
249        11.52         14.93  ...          0.10130           1
238        14.22         27.85  ...          0.08223           1
265        20.73         31.12  ...          0.09469           0

[114 rows x 6 columns]

## GradientBoostingClassifier

In [25]:
gradient_boosting_clf = GradientBoostingClassifier()
gradient_boosting_clf.fit(X_train, y_train)

GradientBoostingClassifier()

In [26]:
gradient_boosting_clf.score(X_test, y_test)

0.9473684210526315

In [27]:
X_test

mean_radius  mean_texture  mean_perimeter  mean_area  mean_smoothness
204        12.47         18.60           81.09      481.9          0.09965
70         18.94         21.31          123.60     1130.0          0.09009
131        15.46         19.48          101.70      748.9          0.10920
431        12.40         17.68           81.47      467.8          0.10540
540        11.54         14.44           74.65      402.9          0.09984
..           ...           ...             ...        ...              ...
486        14.64         16.85           94.21      666.0          0.08641
75         16.07         19.65          104.10      817.7          0.09168
249        11.52         14.93           73.87      406.3          0.10130
238        14.22         27.85           92.55      623.9          0.08223
265        20.73         31.12          135.70     1419.0          0.09469

[114 rows x 5 columns]

In [28]:
gradient_boosting_clf_pred = gradient_boosting_clf.predict(X_test)
gradient_boosting_clf_pred

array([1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 0])

In [29]:
Gradient_Boosting = pd.DataFrame(X_test)
Gradient_Boosting['prediction'] = gradient_boosting_clf_pred
Gradient_Boosting

mean_radius  mean_texture  ...  mean_smoothness  prediction
204        12.47         18.60  ...          0.09965           1
70         18.94         21.31  ...          0.09009           0
131        15.46         19.48  ...          0.10920           0
431        12.40         17.68  ...          0.10540           1
540        11.54         14.44  ...          0.09984           1
..           ...           ...  ...              ...         ...
486        14.64         16.85  ...          0.08641           1
75         16.07         19.65  ...          0.09168           0
249        11.52         14.93  ...          0.10130           1
238        14.22         27.85  ...          0.08223           1
265        20.73         31.12  ...          0.09469           0

[114 rows x 6 columns]

## RandomForestClassifier

In [30]:
rf_clf = RandomForestClassifier()
rf_clf.fit(X_train, y_train)

RandomForestClassifier()

In [32]:
rf_clf.score(X_test, y_test)

0.956140350877193

In [33]:
X_test

mean_radius  mean_texture  mean_perimeter  mean_area  mean_smoothness
204        12.47         18.60           81.09      481.9          0.09965
70         18.94         21.31          123.60     1130.0          0.09009
131        15.46         19.48          101.70      748.9          0.10920
431        12.40         17.68           81.47      467.8          0.10540
540        11.54         14.44           74.65      402.9          0.09984
..           ...           ...             ...        ...              ...
486        14.64         16.85           94.21      666.0          0.08641
75         16.07         19.65          104.10      817.7          0.09168
249        11.52         14.93           73.87      406.3          0.10130
238        14.22         27.85           92.55      623.9          0.08223
265        20.73         31.12          135.70     1419.0          0.09469

[114 rows x 5 columns]

In [34]:
random_forest_clf = rf_clf.predict(X_test)
random_forest_clf

array([1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 0])

In [35]:
Random_Forest = pd.DataFrame(X_test)
Random_Forest['prediction'] = random_forest_clf
Random_Forest

mean_radius  mean_texture  ...  mean_smoothness  prediction
204        12.47         18.60  ...          0.09965           1
70         18.94         21.31  ...          0.09009           0
131        15.46         19.48  ...          0.10920           0
431        12.40         17.68  ...          0.10540           1
540        11.54         14.44  ...          0.09984           1
..           ...           ...  ...              ...         ...
486        14.64         16.85  ...          0.08641           1
75         16.07         19.65  ...          0.09168           0
249        11.52         14.93  ...          0.10130           1
238        14.22         27.85  ...          0.08223           1
265        20.73         31.12  ...          0.09469           0

[114 rows x 6 columns]

In [ ]:
HistGradientBoostingClassifier

## VotingClassifier

In [41]:
# Create individual models
rf = RandomForestClassifier(random_state=42)
lr = LogisticRegression(max_iter=1000, random_state=42)
svc = SVC(probability=True, random_state=42)

# Create VotingClassifier with proper format: [(name, estimator), ...]
voting_classifier = VotingClassifier(estimators=[
    ('rf', rf),
    ('lr', lr),
    ('svc', svc)
])

# Now fit the classifier
voting_classifier.fit(X_train, y_train)

VotingClassifier(estimators=[('rf', RandomForestClassifier(random_state=42)),
                             ('lr',
                              LogisticRegression(max_iter=1000,
                                                 random_state=42)),
                             ('svc', SVC(probability=True, random_state=42))])

In [43]:
voting_classifier.score(X_test, y_test)

0.9473684210526315

In [44]:
vot_clf = voting_classifier.predict(X_test)
vot_clf

array([1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 0])

In [45]:
Voting_Classifier = pd.DataFrame(X_test)
Voting_Classifier['prediction'] = vot_clf
Voting_Classifier

mean_radius  mean_texture  ...  mean_smoothness  prediction
204        12.47         18.60  ...          0.09965           1
70         18.94         21.31  ...          0.09009           0
131        15.46         19.48  ...          0.10920           0
431        12.40         17.68  ...          0.10540           1
540        11.54         14.44  ...          0.09984           1
..           ...           ...  ...              ...         ...
486        14.64         16.85  ...          0.08641           1
75         16.07         19.65  ...          0.09168           0
249        11.52         14.93  ...          0.10130           1
238        14.22         27.85  ...          0.08223           1
265        20.73         31.12  ...          0.09469           0

[114 rows x 6 columns]

In [42]:
# Create a VotingClassifier with hard voting
hard_voting = VotingClassifier(
    estimators=[('rf', rf), ('lr', lr), ('svc', svc)],
    voting='hard'
)

# Create a VotingClassifier with soft voting
soft_voting = VotingClassifier(
    estimators=[('rf', rf), ('lr', lr), ('svc', svc)],
    voting='soft'
)

# With weighted voting (giving more importance to RandomForest)
weighted_voting = VotingClassifier(
    estimators=[('rf', rf), ('lr', lr), ('svc', svc)],
    voting='soft',
    weights=[2, 1, 1]  # RF has double the weight
)

## HistGradientBoostingClassifier

In [47]:
hist_gr_boost_clf = HistGradientBoostingClassifier()
hist_gr_boost_clf.fit(X_train, y_train)

HistGradientBoostingClassifier()

In [48]:
hist_gr_boost_clf.score(X_test, y_test)

0.9736842105263158

In [50]:
X_test

mean_radius  mean_texture  mean_perimeter  mean_area  mean_smoothness
204        12.47         18.60           81.09      481.9          0.09965
70         18.94         21.31          123.60     1130.0          0.09009
131        15.46         19.48          101.70      748.9          0.10920
431        12.40         17.68           81.47      467.8          0.10540
540        11.54         14.44           74.65      402.9          0.09984
..           ...           ...             ...        ...              ...
486        14.64         16.85           94.21      666.0          0.08641
75         16.07         19.65          104.10      817.7          0.09168
249        11.52         14.93           73.87      406.3          0.10130
238        14.22         27.85           92.55      623.9          0.08223
265        20.73         31.12          135.70     1419.0          0.09469

[114 rows x 5 columns]

In [49]:
hist_gr_boost_clf_pred = hist_gr_boost_clf.predict(X_test)
hist_gr_boost_clf_pred

array([1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 0])

In [51]:
Hist_Gradient_Boosting_Classifier = pd.DataFrame(X_test)
Hist_Gradient_Boosting_Classifier['prediction'] = hist_gr_boost_clf_pred
Hist_Gradient_Boosting_Classifier

mean_radius  mean_texture  ...  mean_smoothness  prediction
204        12.47         18.60  ...          0.09965           1
70         18.94         21.31  ...          0.09009           0
131        15.46         19.48  ...          0.10920           0
431        12.40         17.68  ...          0.10540           1
540        11.54         14.44  ...          0.09984           1
..           ...           ...  ...              ...         ...
486        14.64         16.85  ...          0.08641           1
75         16.07         19.65  ...          0.09168           0
249        11.52         14.93  ...          0.10130           1
238        14.22         27.85  ...          0.08223           1
265        20.73         31.12  ...          0.09469           0

[114 rows x 6 columns]